### ISSUE TITLE
It's not working for me

### ISSUE THREAD

**Issue by jaigm** [fjab76/async-rest#1]
Hello,

Is this still working ?

Thanks!

**Comment by fjab76** [comment]
I just tried and it works fine. Can you let me know what error are you getting?

**Comment by jaigm** [comment]
Actually it was my mistake. I open to tabs in browser chrome for check sync/async. And chrome has a feature that wait the first response for check if can re-use it for the second response, that give me 20 seconds for the second response. I disabled cache from the developer tool and everything works. Thanks man !

**Comment by fjab76** [comment]
you are welcome
